### PR TITLE
add solution with explanation to problem `Roman to Integer`

### PR DESCRIPTION
**Pull request by 7oSkaaa**
## Summary

Add a Solution to the problem, complexity analysis, statement, examples and constraints.

### CODE REVIEW

**Comment by arungudelli** [comment]
@7oSkaaa 

I appreciate your time.

But please include different ways to solve the problem if applicable. And add detailed explanation to the problem soultion. 

See the [Contributing Guide](https://github.com/arungudelli/python.shiksha/blob/main/CONTRIBUTING.md)

**Comment by 7oSkaaa** [comment]
Ok, Loot at it now, but I can't add anything else

**Comment by arungudelli** [comment]
@7oSkaaa Can you please join the [Discord](https://discord.com/invite/VTP7csbcCG) channel we can discuss and proceed further.

**Comment by 7oSkaaa** [comment]
OK, but can merge the PR and add hacktoberfest-accepted label

**Comment by 7oSkaaa** [comment]
Can you merge the PR and add hacktoberfest-accepted label

**Comment by arungudelli** [comment]
@7oSkaaa Sorry for the delay.. 

I am expecting article should be detailed as shown below

https://github.com/arungudelli/python.shiksha/blob/main/content/en/problems/string-anagram-python.md 

https://python.shiksha/problems/string-anagram-python/

And if you need help regarding different types of soultion let me know I can help

**Pull request closed without merging**
