### PR TITLE
Added .md file for the problem.

### PR DESCRIPTION
**Pull request by bhoomitri4**
solved issue asked.

### CODE REVIEW

**Review by bhoomitri4 — COMMENTED** [review]
Created a new file successfully.

**Comment by bhoomitri4** [comment]
Please review soon so that necessary changes can be made by me if needed by you.

**Comment by arungudelli** [comment]
@bhoomitri4 Give me some time I will review And let you know..

**Comment by bhoomitri4** [comment]
Ok sir

**Pull request closed without merging**
